{{- if .Values.game2048.host }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app: My2048App
  name: '2048'
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: My2048App
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: My2048App
    spec:
      automountServiceAccountToken: false
      containers:
        - image: alexwhen/docker-2048
          imagePullPolicy: Always
          name: '2048'
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: svc-2048
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: My2048App
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: '2048'
spec:
  hosts:
    - {{ .Values.game2048.host }}
  gateways:
    - yelb-gateway
  http:
    - route:
        - destination:
            host: svc-2048
            port:
              number: 80
      match:
        - uri:
            prefix: /
{{- end }}